spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 78538735264-ifmh4h967kk4e20vavbe8mqcnpuljpbk.apps.googleusercontent.com      #google ClientID
            clientSecret: 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                                #google Secret Password
            scope: email , profile                                                               #요청 정보 범위
          kakao:
            clientId: 3a66a22d3053e987cdd0824f3c563594
            clientSecret: gRoiatzspGYbNJYeUqwyHSdfdqzASlWd
            redirect-uri: http://localhost:8095/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope: profile_nickname # 동의 항목
            #- profile_nickname
            #- profile_image
          # 네이버는 Spring Security를 공식 지원하지 않기 때문에 CommonOAuth2Provider 에서 해주는 값들을 수동으로 입력한다.
          naver:
            client-id: 5EKpDYZtCUfHvTg180KE
            client-secret: BQgpo5Yzeu
            # yml 에서는 / (슬러시)를 그대로 쓰면 파싱 에러가 난다. 따옴표나 작은 따옴표로 감싸주도록 하자.
            # redirect-url 이 아니고 redirect-uri 이다.
            redirect-uri: http://localhost:8095/login/oauth2/code/naver
            # autorization_code가 아니라 authorization_code 이다.
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            # 기준이 되는 user_name 의 이름을 네이버에서는 response로 지정해야한다. (네이버 회원 조회시 반환되는 JSON 형태 떄문이다)
            user-name-attribute: response

